development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://production-host.tld:9292/faye"
  secret_token: "generate_a_hash_for_this"
  signature_expiration: 3600 # one hour
