# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72b65a567c76f7b1e53303c65ed7a2d3eda780190daaa8a79a12b19e4e96f450550e1053cc12d095ab40227efb4553a30f87cb50db85a221e5b5b5b0c3b3a8a1

test:
  secret_key_base: 3e86299880425022501e03109d6f31708c7b01c13b6448f673c9bba3600eb8fa0db63ff9d6f9f1968660683f75a59809171e2c7869f8326c72ee574de028b41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
